### ISSUE TITLE
Declare dependency to fastify-redis

### ISSUE THREAD

**Issue by StarpTech** [lependu/fastify-lured#2]
Hi, great plugin. You can declare `fastify-redis` as plugin dependency.

Look in readme of [`fastify-plugin`](https://github.com/fastify/fastify-plugin)

**Comment by lependu** [comment]
@StarpTech Hi! Thank you for pointing this out for me.

I created a PR(#3), but I had some [issues](https://github.com/fastify/fastify-plugin/issues/17) with this. So I put this on hold until I get some answers.

**Comment by lependu** [comment]
#3
